Repository ezsystems/ezplatform-ee-installer, pull requests merged in 2018-12, with the labels that each got.

#35 EZP-29171: Update Navbar menu items order
  Resources/sql/cleandata.sql
Labels: QA approved, Ready for MERGE

#36 EZEE-2579: Add Workflow schema to eZ Platform EE installer
  Resources/sql/schema.sql
Labels: Improvement, Ready for review

#37 EZEE-2582: Database reinstall fails on ezplatform-workflow package
  Resources/sql/schema.sql
Labels: Bug

#38 EZEE-2582: Database reinstall fails on ezplatform-workflow package
  Resources/sql/schema.sql
Labels: Bug, QA approved

#40 EZP-29936: Synchronize workflow database schema in installers
  Resources/sql/schema.sql
Labels: Improvement, Ready for review

#42 EZEE-2628: Adds missing 'System URL' for 'ez Platform' folder
  Resources/sql/cleandata.sql
Labels: Bug, QA approved, Ready for MERGE
