Repository ezsystems/ezplatform-ee-installer, pull requests merged in 2020-03, with the labels that each got.

#61 EZP-31478: Dropped LSE FullText index from clean EE data
  Resources/sql/mysql/cleandata.sql
  Resources/sql/postgresql/cleandata.sql
Labels: Improvement, QA approved

#62 EZP-31220: Migrated codebase to Symfony 5
  composer.json
Labels: Ready for MERGE

#63 Updated outdated Product name in clean data dumps
  Resources/sql/mysql/cleandata.sql
  Resources/sql/postgresql/cleandata.sql
Labels: Bug

#64 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  composer.json
Labels: Improvement
